### ISSUE TITLE
RTSP link not working into this 

### ISSUE THREAD

**Issue by khyatiChitroda** [yusufcakmak/ExoPlayerSample#29]
I am trying to play rtsp link into this player but it is not working, getting source error.

**Comment by yusufcakmak** [comment]
I'll check, thx

**Comment by khyatiChitroda** [comment]
Thank you....!!!! Please check once and let me know.

**Comment by khyatiChitroda** [comment]
Hello is there any update? I had also tried dev-2 branch but not able to compile, every time it gives error.

**Comment by yusufcakmak** [comment]
could you share your rtsp link ?

**Comment by CMingTseng** [comment]
> Hello is there any update? I had also tried dev-2 branch but not able to compile, every time it gives error.

@khyatiChitroda   @yusufcakmak 


Dear Sir

i clone your project 

and then check it 

the project not dependencies any  RTSP library  !!

it can play RTSP ?

if you can add RTSP

can ref this project  https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/tree/dev/c516740

but need modify some class (because  the rtsp not contain Google OEM ExoPlayer library .this project is mixed & hacked  )

THX

**Comment by yusufcakmak** [comment]
MediaExtractor doesn't support RTSP. you can look at this issue -> google/ExoPlayer#55

I will try to add support but I cant say when.
